name: irx
channels:
  - nodefaults
  - conda-forge
dependencies:
  - clang 14.*
  - clangdev 14.*
  - graphviz
  - python >=3.8.1,<3.12
  - poetry >=1.5
  - nodejs # used by semantic-release
  - shellcheck
