name: irx
channels:
  - nodefaults
  - conda-forge
dependencies:
  - clang 14.*
  - clangdev 14.*
  - graphviz
  - pip
  - poetry >=1.5
  - python 3.8.1,<3.12
  - nodejs # used by semantic-release
  - shellcheck
  - pip:
      # fix issues with distlib
      - paginate
