name: irx
channels:
  - nodefaults
  - conda-forge
dependencies:
  - clang 14.*
  - clangdev 14.*
  - pip
  - poetry >=2
  - python 3.13.*
  - nodejs # used by semantic-release
  - shellcheck
  - llvmlite >=0.41.1
  - pip:
      # fix issues with distlib
      - paginate
      - pyrepl
