"""
title: Semantic analysis package.
"""

from irx.analysis.diagnostics import Diagnostic, DiagnosticBag, SemanticError
from irx.analysis.facade import analyze, analyze_module
from irx.analysis.resolved_nodes import (
    SPECIALIZED_BINARY_OP_EXTRA,
    AddBinOp,
    AssignmentBinOp,
    BitAndBinOp,
    BitOrBinOp,
    BitXorBinOp,
    DivBinOp,
    EqBinOp,
    GeBinOp,
    GtBinOp,
    LeBinOp,
    LogicalAndBinOp,
    LogicalOrBinOp,
    LtBinOp,
    ModBinOp,
    MulBinOp,
    NeBinOp,
    ResolvedAssignment,
    ResolvedOperator,
    SemanticFlags,
    SemanticFunction,
    SemanticInfo,
    SemanticSymbol,
    SubBinOp,
    binary_op_type_for_opcode,
    specialize_binary_op,
)

__all__ = [
    "SPECIALIZED_BINARY_OP_EXTRA",
    "AddBinOp",
    "AssignmentBinOp",
    "BitAndBinOp",
    "BitOrBinOp",
    "BitXorBinOp",
    "Diagnostic",
    "DiagnosticBag",
    "DivBinOp",
    "EqBinOp",
    "GeBinOp",
    "GtBinOp",
    "LeBinOp",
    "LogicalAndBinOp",
    "LogicalOrBinOp",
    "LtBinOp",
    "ModBinOp",
    "MulBinOp",
    "NeBinOp",
    "ResolvedAssignment",
    "ResolvedOperator",
    "SemanticError",
    "SemanticFlags",
    "SemanticFunction",
    "SemanticInfo",
    "SemanticSymbol",
    "SubBinOp",
    "analyze",
    "analyze_module",
    "binary_op_type_for_opcode",
    "specialize_binary_op",
]
