"""
title: Semantic analysis package.
summary: >-
  Re-export the semantic-analysis APIs, semantic-contract types, and sidecar
  metadata used by hosts, tests, and backend lowering.
"""

from irx.analysis.api import (
    SemanticAnalyzer,
    analyze,
    analyze_module,
    analyze_modules,
)
from irx.analysis.contract import (
    PhaseErrorBoundary,
    SemanticContract,
    SemanticPhase,
    get_semantic_contract,
)
from irx.analysis.module_interfaces import (
    ImportResolver,
    ModuleKey,
    ParsedModule,
)
from irx.analysis.resolved_nodes import (
    ClassHeaderFieldKind,
    ClassMemberKind,
    ClassMemberResolutionKind,
    ClassObjectRepresentationKind,
    FFIAdmissibility,
    FFICallableInfo,
    FFILinkStrategy,
    FFITypeClass,
    FFITypeInfo,
    MethodDispatchKind,
    ResolvedAssignment,
    ResolvedClassFieldAccess,
    ResolvedImportBinding,
    ResolvedMethodCall,
    ResolvedOperator,
    SemanticBinding,
    SemanticClass,
    SemanticClassHeaderField,
    SemanticClassLayout,
    SemanticClassLayoutField,
    SemanticClassMember,
    SemanticClassMemberResolution,
    SemanticClassMethodDispatch,
    SemanticClassStaticStorage,
    SemanticFlags,
    SemanticFunction,
    SemanticInfo,
    SemanticModule,
    SemanticStruct,
    SemanticSymbol,
)
from irx.analysis.session import CompilationSession
from irx.diagnostics import Diagnostic, DiagnosticBag, SemanticError

__all__ = [
    "ClassHeaderFieldKind",
    "ClassMemberKind",
    "ClassMemberResolutionKind",
    "ClassObjectRepresentationKind",
    "CompilationSession",
    "Diagnostic",
    "DiagnosticBag",
    "FFIAdmissibility",
    "FFICallableInfo",
    "FFILinkStrategy",
    "FFITypeClass",
    "FFITypeInfo",
    "ImportResolver",
    "MethodDispatchKind",
    "ModuleKey",
    "ParsedModule",
    "PhaseErrorBoundary",
    "ResolvedAssignment",
    "ResolvedClassFieldAccess",
    "ResolvedImportBinding",
    "ResolvedMethodCall",
    "ResolvedOperator",
    "SemanticAnalyzer",
    "SemanticBinding",
    "SemanticClass",
    "SemanticClassHeaderField",
    "SemanticClassLayout",
    "SemanticClassLayoutField",
    "SemanticClassMember",
    "SemanticClassMemberResolution",
    "SemanticClassMethodDispatch",
    "SemanticClassStaticStorage",
    "SemanticContract",
    "SemanticError",
    "SemanticFlags",
    "SemanticFunction",
    "SemanticInfo",
    "SemanticModule",
    "SemanticPhase",
    "SemanticStruct",
    "SemanticSymbol",
    "analyze",
    "analyze_module",
    "analyze_modules",
    "get_semantic_contract",
]
